/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magicbill;

/**
 *
 * @author Hameed Ahmed
 */
import java.sql.*;
import javax.swing.JOptionPane;

public class CounterNoteSet extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;

    /**
     * Creates new form CounterNoteSet
     */
    public CounterNoteSet() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        Connect();
        
        
        String sqlret = "select number from counternotes";
        try{
        rs = stmt.executeQuery(sqlret);
        /**Getting no of rs1 coins from DB**/
        
        rs.next();
        String rrs1s=rs.getString("number");
        jTextField1.setText(rrs1s);
        
        /**Getting no of rs2 coins from DB**/
        rs.next();
        String rrs2s=rs.getString("number");
        jTextField2.setText(rrs2s);
        
        rs.next();
        String rrs5s=rs.getString("number");
        jTextField3.setText(rrs5s);
        
        rs.next();
        String rrs10s=rs.getString("number");
        jTextField7.setText(rrs10s);
        
        rs.next();
        String rrs10coin=rs.getString("number");
        jTextField13.setText(rrs10coin);
        
        rs.next();
        String rrs20s=rs.getString("number");
        jTextField8.setText(rrs20s);
        
        rs.next();
        String rrs50s=rs.getString("number");
        jTextField9.setText(rrs50s);
        
        rs.next();
        String rrs100s=rs.getString("number");
        jTextField10.setText(rrs100s);
        
        rs.next();
        String rrs200s=rs.getString("number");
        jTextField4.setText(rrs200s);
        
        rs.next();
        String rrs500s=rs.getString("number");
        jTextField5.setText(rrs500s);
        
        rs.next();
        String rrs2000s=rs.getString("number");
        jTextField6.setText(rrs2000s);
        

        
        
        
        }
        catch(Exception exe){
            JOptionPane.showMessageDialog(this, exe.getMessage());
                  
        }
        
      
        
    }
    
    public void Connect(){
        try{
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cashcounter","root","12MMAZ11");
        stmt = con.createStatement();
        
        }
        catch(Exception ex){
              
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        button14 = new java.awt.Button();
        button15 = new java.awt.Button();
        button16 = new java.awt.Button();
        button17 = new java.awt.Button();
        button18 = new java.awt.Button();
        button19 = new java.awt.Button();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        button20 = new java.awt.Button();
        button21 = new java.awt.Button();
        button22 = new java.awt.Button();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField1.setText("0");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(50, 410, 85, 30);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(260, 410, 85, 30);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField3.setText("0");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(450, 410, 85, 30);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField4.setText("0");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(1290, 30, 85, 30);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField5.setText("0");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(1290, 230, 85, 30);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField6.setText("0");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(1290, 430, 85, 30);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField7.setText("0");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(760, 20, 85, 30);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField8.setText("0");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(760, 230, 85, 30);

        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField9.setText("0");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(760, 430, 85, 30);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField10.setText("0");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(760, 630, 85, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs1 coin png.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 450, 110, 110);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs2 coin png.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 450, 120, 110);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 5 png.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 440, 120, 130);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs10 new.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(640, 50, 349, 156);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs20 new.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 260, 349, 156);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 50 new.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 460, 348, 156);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 200 new.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1160, 60, 350, 156);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 500 new.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1160, 260, 350, 156);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 2000 new.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1160, 460, 350, 156);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs100 new.jpg"))); // NOI18N
        jLabel12.setText("jLabel1");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(640, 660, 350, 150);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 3, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter new denominationa to be updated in cash counter");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 590, 330);

        button1.setBackground(new java.awt.Color(51, 255, 51));
        button1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button1.setLabel("+");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(840, 20, 40, 30);

        button2.setBackground(new java.awt.Color(255, 0, 0));
        button2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button2.setLabel("-");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(720, 20, 40, 30);

        button3.setBackground(new java.awt.Color(51, 255, 51));
        button3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button3.setLabel("+");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3);
        button3.setBounds(840, 230, 40, 30);

        button4.setBackground(new java.awt.Color(255, 0, 0));
        button4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button4.setLabel("-");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4);
        button4.setBounds(720, 230, 40, 30);

        button5.setBackground(new java.awt.Color(255, 0, 0));
        button5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button5.setLabel("-");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5);
        button5.setBounds(410, 410, 40, 30);

        button6.setBackground(new java.awt.Color(51, 255, 51));
        button6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button6.setLabel("+");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6);
        button6.setBounds(530, 410, 40, 30);

        button7.setBackground(new java.awt.Color(255, 0, 0));
        button7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button7.setLabel("-");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7);
        button7.setBounds(720, 430, 40, 30);

        button8.setBackground(new java.awt.Color(51, 255, 51));
        button8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button8.setLabel("+");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8);
        button8.setBounds(840, 430, 40, 30);

        button9.setBackground(new java.awt.Color(255, 0, 0));
        button9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button9.setLabel("-");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        getContentPane().add(button9);
        button9.setBounds(720, 630, 40, 30);

        button10.setBackground(new java.awt.Color(51, 255, 51));
        button10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button10.setLabel("+");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        getContentPane().add(button10);
        button10.setBounds(840, 630, 40, 30);

        button11.setBackground(new java.awt.Color(255, 0, 0));
        button11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button11.setLabel("-");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        getContentPane().add(button11);
        button11.setBounds(220, 570, 40, 30);

        button12.setBackground(new java.awt.Color(51, 255, 51));
        button12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button12.setLabel("+");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        getContentPane().add(button12);
        button12.setBounds(350, 570, 40, 30);

        button13.setBackground(new java.awt.Color(255, 0, 0));
        button13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button13.setLabel("-");
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        getContentPane().add(button13);
        button13.setBounds(10, 410, 40, 30);

        button14.setBackground(new java.awt.Color(51, 255, 51));
        button14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button14.setLabel("+");
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        getContentPane().add(button14);
        button14.setBounds(130, 410, 40, 30);

        button15.setBackground(new java.awt.Color(51, 255, 51));
        button15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button15.setLabel("+");
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });
        getContentPane().add(button15);
        button15.setBounds(1370, 30, 40, 30);

        button16.setBackground(new java.awt.Color(255, 0, 0));
        button16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button16.setLabel("-");
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });
        getContentPane().add(button16);
        button16.setBounds(1250, 30, 40, 30);

        button17.setBackground(new java.awt.Color(255, 0, 0));
        button17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button17.setLabel("-");
        button17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button17ActionPerformed(evt);
            }
        });
        getContentPane().add(button17);
        button17.setBounds(1250, 230, 40, 30);

        button18.setBackground(new java.awt.Color(51, 255, 51));
        button18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button18.setLabel("+");
        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });
        getContentPane().add(button18);
        button18.setBounds(1370, 230, 40, 30);

        button19.setBackground(new java.awt.Color(51, 255, 51));
        button19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button19.setLabel("+");
        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });
        getContentPane().add(button19);
        button19.setBounds(1370, 430, 40, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs10 coin.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(250, 600, 120, 120);

        jTextField13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField13.setText("0");
        getContentPane().add(jTextField13);
        jTextField13.setBounds(260, 570, 90, 30);

        button20.setBackground(new java.awt.Color(255, 0, 0));
        button20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button20.setLabel("-");
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        getContentPane().add(button20);
        button20.setBounds(1250, 430, 40, 30);

        button21.setBackground(new java.awt.Color(51, 255, 51));
        button21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button21.setLabel("+");
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });
        getContentPane().add(button21);
        button21.setBounds(340, 410, 40, 30);

        button22.setBackground(new java.awt.Color(255, 0, 0));
        button22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button22.setLabel("-");
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });
        getContentPane().add(button22);
        button22.setBounds(220, 410, 40, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/simple-light-color-tone-nude-pink-background-free-photo.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1690, 940);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int irs1=Integer.parseInt(jTextField1.getText());
        int irs2=Integer.parseInt(jTextField2.getText());
        int irs5=Integer.parseInt(jTextField3.getText());
        int irs10=Integer.parseInt(jTextField7.getText());
        int irs10coin=Integer.parseInt(jTextField13.getText());
        int irs20=Integer.parseInt(jTextField8.getText());
        int irs50=Integer.parseInt(jTextField9.getText());
        int irs100=Integer.parseInt(jTextField10.getText());
        int irs200=Integer.parseInt(jTextField4.getText());
        int irs500=Integer.parseInt(jTextField5.getText());
        int irs2000=Integer.parseInt(jTextField6.getText());

        try{

            int m=0,n=0;

            String sql1="update counternotes set number="+irs1+" where note='rs1'";
            n =stmt.executeUpdate(sql1);
            if(n==1){m=m+1;}
            n=0;

            String sql2="update counternotes set number="+irs2+" where note='rs2'";
            n=stmt.executeUpdate(sql2);
            if(n==1){m=m+1;}
            n=0;

            String sql5="update counternotes set number="+irs5+" where note='rs5'";
            n=stmt.executeUpdate(sql5);
            if(n==1){m=m+1;}
            n=0;

            String sql10="update counternotes set number="+irs10+" where note='rs10'";
            n=stmt.executeUpdate(sql10);
            if(n==1){m=m+1;}
            n=0;
            
            String sql10coin="update counternotes set number="+irs10coin+" where note='rs10coin'";
            n=stmt.executeUpdate(sql10coin);
            if(n==1){m=m+1;}
            n=0;

            String sql20="update counternotes set number="+irs20+" where note='rs20'";
            n=stmt.executeUpdate(sql20);
            if(n==1){m=m+1;}
            n=0;

            String sql50="update counternotes set number="+irs50+" where note='rs50'";
            n=stmt.executeUpdate(sql50);
            if(n==1){m=m+1;}
            n=0;

            String sql100="update counternotes set number="+irs100+" where note='rs100'";
            n=stmt.executeUpdate(sql100);
            if(n==1){m=m+1;}
            n=0;

            String sql200="update counternotes set number="+irs200+" where note='rs200'";
            n=stmt.executeUpdate(sql200);
            if(n==1){m=m+1;}
            n=0;

            String sql500="update counternotes set number="+irs500+" where note='rs500'";
            n=stmt.executeUpdate(sql500);
            if(n==1){m=m+1;}
            n=0;

            String sql2000="update counternotes set number="+irs2000+" where note='rs2000'";
            n=stmt.executeUpdate(sql2000);
            if(n==1){m=m+1;}

            if(m==11){

                JOptionPane.showMessageDialog(this,"Denominations successfully updated in the cash counter","SUCCESS",JOptionPane.CLOSED_OPTION);

            }

        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

        MainFrame mfobj = new MainFrame();

        mfobj.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
    jTextField3.setText((Integer.parseInt(jTextField3.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
    jTextField10.setText((Integer.parseInt(jTextField10.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button9ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        jTextField13.setText((Integer.parseInt(jTextField13.getText())-1)+"");            // TODO add your handling code here:
    }//GEN-LAST:event_button11ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
    jTextField1.setText((Integer.parseInt(jTextField1.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button13ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        jTextField7.setText((Integer.parseInt(jTextField7.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
    jTextField1.setText((Integer.parseInt(jTextField1.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button14ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
    jTextField13.setText((Integer.parseInt(jTextField13.getText())+1)+"");           // TODO add your handling code here:
    }//GEN-LAST:event_button12ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
    jTextField3.setText((Integer.parseInt(jTextField3.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
    jTextField7.setText((Integer.parseInt(jTextField7.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
    jTextField8.setText((Integer.parseInt(jTextField8.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
    jTextField8.setText((Integer.parseInt(jTextField8.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
    jTextField9.setText((Integer.parseInt(jTextField9.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button8ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        jTextField9.setText((Integer.parseInt(jTextField9.getText())-1)+"");            // TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
    jTextField10.setText((Integer.parseInt(jTextField10.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button10ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
    jTextField4.setText((Integer.parseInt(jTextField4.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button15ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed
    jTextField4.setText((Integer.parseInt(jTextField4.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button16ActionPerformed

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button18ActionPerformed
    jTextField5.setText((Integer.parseInt(jTextField5.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button18ActionPerformed

    private void button17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button17ActionPerformed
    jTextField5.setText((Integer.parseInt(jTextField5.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button17ActionPerformed

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button19ActionPerformed
    jTextField6.setText((Integer.parseInt(jTextField6.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button19ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
    jTextField6.setText((Integer.parseInt(jTextField6.getText())-1)+"");        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_button20ActionPerformed

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed
        jTextField2.setText((Integer.parseInt(jTextField2.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button21ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed
        jTextField2.setText((Integer.parseInt(jTextField2.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CounterNoteSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CounterNoteSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CounterNoteSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CounterNoteSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CounterNoteSet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button14;
    private java.awt.Button button15;
    private java.awt.Button button16;
    private java.awt.Button button17;
    private java.awt.Button button18;
    private java.awt.Button button19;
    private java.awt.Button button2;
    private java.awt.Button button20;
    private java.awt.Button button21;
    private java.awt.Button button22;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
