/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magicbill;

import javax.swing.JOptionPane;
import java.sql.*;
import java.lang.Math;

/**
 *
 * @author Hameed Ahmed
 */
public class MainFrame extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        Connect();
        jTextField1.setText(GlobalClass.invamt+"");
    }
    
    public void Connect(){
        try{
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cashcounter","root","12MMAZ11");
        stmt = con.createStatement();
        
        }
        catch(Exception ex){
            
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        button13 = new java.awt.Button();
        button14 = new java.awt.Button();
        button11 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button2 = new java.awt.Button();
        button1 = new java.awt.Button();
        button4 = new java.awt.Button();
        button3 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button19 = new java.awt.Button();
        button18 = new java.awt.Button();
        button17 = new java.awt.Button();
        button16 = new java.awt.Button();
        button15 = new java.awt.Button();
        button20 = new java.awt.Button();
        button12 = new java.awt.Button();
        jButton2 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        button21 = new java.awt.Button();
        button22 = new java.awt.Button();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs100 new.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(640, 670, 350, 150);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 50 new.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 470, 348, 156);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 2000 new.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1130, 670, 350, 156);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs20 new.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 270, 349, 156);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 200 new.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1130, 250, 350, 156);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 500 new.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1130, 460, 350, 156);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs1 coin png.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 440, 120, 110);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs10 coin.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 610, 120, 120);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 5 png.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(430, 450, 110, 110);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Enter Input Denominations from customer:-");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(42, 43, 459, 71);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Enter invoice Amount:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(110, 190, 190, 28);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 190, 149, 28);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField2.setText("0");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(50, 410, 85, 30);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField3.setText("0");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(260, 410, 85, 30);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField4.setText("0");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(450, 410, 85, 30);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField5.setText("0");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(1260, 630, 85, 30);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField6.setText("0");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(1260, 420, 85, 30);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField7.setText("0");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(1260, 210, 85, 30);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField8.setText("0");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(760, 630, 85, 30);

        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField9.setText("0");
        jTextField9.setBorder(null);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(760, 430, 85, 30);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField10.setText("0");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(760, 230, 85, 30);

        jTextField11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField11.setText("0");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(760, 20, 85, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("DONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 250, 120, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs10 new.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(640, 60, 349, 156);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 3, true));
        jPanel2.setOpaque(false);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 30, 520, 280);

        button13.setBackground(new java.awt.Color(255, 0, 0));
        button13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button13.setLabel("-");
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        getContentPane().add(button13);
        button13.setBounds(10, 410, 40, 30);

        button14.setBackground(new java.awt.Color(51, 255, 51));
        button14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button14.setLabel("+");
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        getContentPane().add(button14);
        button14.setBounds(130, 410, 40, 30);

        button11.setBackground(new java.awt.Color(255, 0, 0));
        button11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button11.setLabel("-");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        getContentPane().add(button11);
        button11.setBounds(220, 410, 40, 30);

        button5.setBackground(new java.awt.Color(255, 0, 0));
        button5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button5.setLabel("-");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5);
        button5.setBounds(410, 410, 40, 30);

        button6.setBackground(new java.awt.Color(51, 255, 51));
        button6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button6.setLabel("+");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6);
        button6.setBounds(530, 410, 40, 30);

        button2.setBackground(new java.awt.Color(255, 0, 0));
        button2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button2.setLabel("-");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(720, 20, 40, 30);

        button1.setBackground(new java.awt.Color(51, 255, 51));
        button1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button1.setLabel("+");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(840, 20, 40, 30);

        button4.setBackground(new java.awt.Color(255, 0, 0));
        button4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button4.setLabel("-");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4);
        button4.setBounds(720, 230, 40, 30);

        button3.setBackground(new java.awt.Color(51, 255, 51));
        button3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button3.setLabel("+");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3);
        button3.setBounds(840, 230, 40, 30);

        button7.setBackground(new java.awt.Color(255, 0, 0));
        button7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button7.setLabel("-");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7);
        button7.setBounds(720, 430, 40, 30);

        button8.setBackground(new java.awt.Color(51, 255, 51));
        button8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button8.setLabel("+");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8);
        button8.setBounds(840, 430, 40, 30);

        button9.setBackground(new java.awt.Color(255, 0, 0));
        button9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button9.setLabel("-");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        getContentPane().add(button9);
        button9.setBounds(720, 630, 40, 30);

        button10.setBackground(new java.awt.Color(51, 255, 51));
        button10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button10.setLabel("+");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        getContentPane().add(button10);
        button10.setBounds(840, 630, 40, 30);

        button19.setBackground(new java.awt.Color(51, 255, 51));
        button19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button19.setLabel("+");
        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });
        getContentPane().add(button19);
        button19.setBounds(1340, 630, 40, 30);

        button18.setBackground(new java.awt.Color(51, 255, 51));
        button18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button18.setLabel("+");
        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });
        getContentPane().add(button18);
        button18.setBounds(1340, 420, 40, 30);

        button17.setBackground(new java.awt.Color(255, 0, 0));
        button17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button17.setLabel("-");
        button17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button17ActionPerformed(evt);
            }
        });
        getContentPane().add(button17);
        button17.setBounds(1220, 420, 40, 30);

        button16.setBackground(new java.awt.Color(255, 0, 0));
        button16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button16.setLabel("-");
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });
        getContentPane().add(button16);
        button16.setBounds(1220, 210, 40, 30);

        button15.setBackground(new java.awt.Color(51, 255, 51));
        button15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button15.setLabel("+");
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });
        getContentPane().add(button15);
        button15.setBounds(1340, 210, 40, 30);

        button20.setBackground(new java.awt.Color(255, 0, 0));
        button20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button20.setLabel("-");
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        getContentPane().add(button20);
        button20.setBounds(1220, 630, 40, 30);

        button12.setBackground(new java.awt.Color(51, 255, 51));
        button12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button12.setLabel("+");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        getContentPane().add(button12);
        button12.setBounds(340, 410, 40, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Edit Notes in Cash Counter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1160, 40, 280, 50);

        jTextField13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField13.setText("0");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13);
        jTextField13.setBounds(260, 580, 90, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs2 coin png.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(250, 440, 120, 120);

        button21.setBackground(new java.awt.Color(51, 255, 51));
        button21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button21.setLabel("+");
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });
        getContentPane().add(button21);
        button21.setBounds(350, 580, 40, 30);

        button22.setBackground(new java.awt.Color(255, 0, 0));
        button22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button22.setLabel("-");
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });
        getContentPane().add(button22);
        button22.setBounds(220, 580, 40, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/simple-light-color-tone-nude-pink-background-free-photo.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, -30, 1730, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Storing input denominations in global variables
        
        GlobalClass.iprs1=Integer.parseInt(jTextField2.getText());
        GlobalClass.iprs2=Integer.parseInt(jTextField3.getText());
        GlobalClass.iprs5=Integer.parseInt(jTextField4.getText());
        GlobalClass.iprs10=Integer.parseInt(jTextField11.getText());
        GlobalClass.iprs10coin=Integer.parseInt(jTextField13.getText());
        GlobalClass.iprs20=Integer.parseInt(jTextField10.getText());
        GlobalClass.iprs50=Integer.parseInt(jTextField9.getText());
        GlobalClass.iprs100=Integer.parseInt(jTextField8.getText());
        GlobalClass.iprs200=Integer.parseInt(jTextField7.getText());
        GlobalClass.iprs500=Integer.parseInt(jTextField6.getText());
        GlobalClass.iprs2000=Integer.parseInt(jTextField5.getText());
        // input from invoice amount box to global variables.
        GlobalClass.invamt=Integer.parseInt(jTextField1.getText());
        
        
        
        GlobalClass.ipamt=GlobalClass.iprs1*1+GlobalClass.iprs2*2+GlobalClass.iprs5*5+GlobalClass.iprs10*10+GlobalClass.iprs10coin*10+GlobalClass.iprs20*20+GlobalClass.iprs50*50+GlobalClass.iprs100*100+GlobalClass.iprs200*200+GlobalClass.iprs500*500+GlobalClass.iprs2000*2000;
        
        
        if(GlobalClass.invamt>GlobalClass.ipamt)
        {
            JOptionPane.showMessageDialog(this,"The Invoice Amount is greater than the amount collected from the customer","ERROR",JOptionPane.ERROR_MESSAGE);
             
        }
        
        //getting notes from cashcounter/ database.
        
        else{
            int ccrs1=0;
            int ccrs2=0;
            int ccrs5=0;
            int ccrs10=0;
            int ccrs10coins=0;
            int ccrs20=0;
            int ccrs50=0;
            int ccrs100=0;
            int ccrs200=0;
            int ccrs500=0;
            int ccrs2000=0;
            
            
            //Getting no of notes from cash counter, i.e from database...
            String sqlret = "select number from counternotes";
            try{
                
            rs = stmt.executeQuery(sqlret);
            rs.next();
            String rrs1s=rs.getString("number");
            ccrs1=Integer.parseInt(rrs1s);
            

            
            rs.next();
            String rrs2s=rs.getString("number");
            ccrs2=Integer.parseInt(rrs2s);
            
            rs.next();
            String rrs5s=rs.getString("number");
            ccrs5=Integer.parseInt(rrs5s);
            
            rs.next();
            String rrs10s=rs.getString("number");
            ccrs10=Integer.parseInt(rrs10s);
            
            rs.next();
            String rrs10coins=rs.getString("number");
            ccrs10coins=Integer.parseInt(rrs10coins);
            
            rs.next();
            String rrs20s=rs.getString("number");
            ccrs20=Integer.parseInt(rrs20s);
            
            rs.next();
            String rrs50s=rs.getString("number");
            ccrs50=Integer.parseInt(rrs50s);
            
            rs.next();
            String rrs100s=rs.getString("number");
            ccrs100=Integer.parseInt(rrs100s);
            
            rs.next();
            String rrs200s=rs.getString("number");
            ccrs200=Integer.parseInt(rrs200s);
            
            rs.next();
            String rrs500s=rs.getString("number");
            ccrs500=Integer.parseInt(rrs500s);
            
            rs.next();
            String rrs2000s=rs.getString("number");
            ccrs2000=Integer.parseInt(rrs2000s);
            
            }
            catch(Exception exe){
            JOptionPane.showMessageDialog(this, exe.getMessage());
                  
            }
            
            ccrs1=ccrs1+GlobalClass.iprs1;
            ccrs2=ccrs2+GlobalClass.iprs2;
            ccrs5=ccrs5+GlobalClass.iprs5;
            ccrs10=ccrs10+GlobalClass.iprs10;
            ccrs10coins=ccrs10coins+GlobalClass.iprs10coin;
            ccrs20=ccrs20+GlobalClass.iprs20;
            ccrs50=ccrs50+GlobalClass.iprs50;
            ccrs100=ccrs100+GlobalClass.iprs100;
            ccrs200=ccrs200+GlobalClass.iprs200;
            ccrs500=ccrs500+GlobalClass.iprs500;
            ccrs2000=ccrs2000+GlobalClass.iprs2000;
            
            float gbamt=GlobalClass.ipamt-GlobalClass.invamt;
            
            if(gbamt/2000>=1)
            {
                if(Math.floor(gbamt/2000)<=ccrs2000)  //checking Notes availability in cashcounter
                {
                    GlobalClass.oprs2000=(int)Math.floor(gbamt/2000);
                    ccrs2000=ccrs2000-GlobalClass.oprs2000;
                    
                }
                else
                {
                    GlobalClass.oprs2000=ccrs2000;
                    ccrs2000=0;
                }
                gbamt=gbamt-GlobalClass.oprs2000*2000;
                    
            }
            
            else{GlobalClass.oprs2000=0;}
            
            if(gbamt/500>=1)
            {
                if(Math.floor(gbamt/500)<=ccrs500)  //Notes are available in cashcounter
                {
                    GlobalClass.oprs500=(int)Math.floor(gbamt/500);
                    ccrs500=ccrs500-GlobalClass.oprs500;
                    
                }
                else
                {
                    GlobalClass.oprs500=ccrs500;
                    ccrs500=0;
                }
                gbamt=gbamt-GlobalClass.oprs500*500;
                    
            }
            else{GlobalClass.oprs500=0;}
            
            if(gbamt/200>=1)
            {
                if(Math.floor(gbamt/200)<=ccrs200)  //Notes are available in cashcounter
                {
                    GlobalClass.oprs200=(int)Math.floor(gbamt/200);
                    ccrs200=ccrs200-GlobalClass.oprs200;
                    
                }
                else
                {
                    GlobalClass.oprs200=ccrs200;
                    ccrs200=0;
                }
                gbamt=gbamt-GlobalClass.oprs200*200;
                    
            }
            else{GlobalClass.oprs200=0;}
            
            if(gbamt/100>=1)
            {
                if(Math.floor(gbamt/100)<=ccrs100)  //Notes are available in cashcounter
                {
                    GlobalClass.oprs100=(int)Math.floor(gbamt/100);
                    ccrs100=ccrs100-GlobalClass.oprs100;
                    
                }
                else
                {
                    GlobalClass.oprs100=ccrs100;
                    ccrs100=0;
                }
                gbamt=gbamt-GlobalClass.oprs100*100;
                    
            }
            else{GlobalClass.oprs100=0;}
            
            if(gbamt/50>=1)
            {
                if(Math.floor(gbamt/50)<=ccrs50)  //Notes are available in cashcounter
                {
                    GlobalClass.oprs50=(int)Math.floor(gbamt/50);
                    ccrs50=ccrs50-GlobalClass.oprs50;
                    
                }
                else
                {
                    GlobalClass.oprs50=ccrs50;
                    ccrs50=0;
                }
                gbamt=gbamt-GlobalClass.oprs50*50;
                    
            }
            else{GlobalClass.oprs50=0;}
            
            if(gbamt/20>=1)
            {
                if(Math.floor(gbamt/20)<=ccrs20)  //Notes are available in cashcounter
                {
                    GlobalClass.oprs20=(int)Math.floor(gbamt/20);
                    ccrs20=ccrs20-GlobalClass.oprs20;
                    
                }
                else
                {
                    GlobalClass.oprs20=ccrs20;
                    ccrs20=0;
                }
                gbamt=gbamt-GlobalClass.oprs20*20;
                    
            }
            else{GlobalClass.oprs20=0;}
            
            if(gbamt/10>=1)
            {
                if(Math.floor(gbamt/10)<=ccrs10)  //Notes are available in cashcounter
                {
                    GlobalClass.oprs10=(int)Math.floor(gbamt/10);
                    ccrs10=ccrs10-GlobalClass.oprs10;
                    
                }
                else
                {
                    GlobalClass.oprs10=ccrs10;
                    ccrs10=0;
                }
                gbamt=gbamt-GlobalClass.oprs10*10;
                    
            }
            else{GlobalClass.oprs10=0;}
            
            if(gbamt/10>=1)
            {
                if(Math.floor(gbamt/10)<=ccrs10coins)  //coins are available in cashcounter
                {
                    GlobalClass.oprs10coin=(int)Math.floor(gbamt/10);
                    ccrs10coins=ccrs10coins-GlobalClass.oprs10coin;
                    
                }
                else
                {
                    GlobalClass.oprs10coin=ccrs10coins;
                    ccrs10coins=0;
                }
                gbamt=gbamt-GlobalClass.oprs10coin*10;
                    
            }
            else{GlobalClass.oprs10coin=0;}
            
            if(gbamt/5>=1)
            {
                if(Math.floor(gbamt/5)<=ccrs5)  //Notes are available in cashcounter
                {
                    GlobalClass.oprs5=(int)Math.floor(gbamt/5);
                    ccrs5=ccrs5-GlobalClass.oprs5;
                    
                }
                else
                {
                    GlobalClass.oprs5=ccrs5;
                    ccrs5=0;
                }
                gbamt=gbamt-GlobalClass.oprs5*5;
                    
            }
            else{GlobalClass.oprs5=0;}
            
            if(gbamt/2>=1)
            {
                if(Math.floor(gbamt/2)<=ccrs2)  //Notes are available in cashcounter
                {
                    GlobalClass.oprs2=(int)Math.floor(gbamt/2);
                    ccrs2=ccrs2-GlobalClass.oprs2;
                    
                }
                else
                {
                    GlobalClass.oprs2=ccrs2;
                    ccrs2=0;
                }
                gbamt=gbamt-GlobalClass.oprs2*2;
                    
            }
            else{GlobalClass.oprs2=0;}
            
            if(gbamt/1>=1)
            {
                if(Math.floor(gbamt/1)<=ccrs1)  //Notes are available in cashcounter
                {
                    GlobalClass.oprs1=(int)Math.floor(gbamt/1);
                    ccrs1=ccrs1-GlobalClass.oprs1;
                    
                }
                else
                {
                    GlobalClass.oprs1=ccrs1;
                    ccrs1=0;
                }
                gbamt=gbamt-GlobalClass.oprs1*1;
                    
            }
            else{GlobalClass.oprs1=0;}
            
            if(gbamt>0)
            {
                JOptionPane.showMessageDialog(this,"Insufficient denominations in the cash counter, ask for lower denomination from the customer","Insufficient denominations in the cash counter",JOptionPane.ERROR_MESSAGE);
            
            }
            
            else{
            
            //Updating the cash counter:  database
            
            try{
            
        
         
         
        String sql1="update counternotes set number="+ccrs1+" where note='rs1'";
        stmt.executeUpdate(sql1);
        
        
        String sql2="update counternotes set number="+ccrs2+" where note='rs2'";
        stmt.executeUpdate(sql2);
        
                
        String sql5="update counternotes set number="+ccrs5+" where note='rs5'";
        stmt.executeUpdate(sql5);
        
                
        String sql10="update counternotes set number="+ccrs10+" where note='rs10'";
        stmt.executeUpdate(sql10);
        
        String sql10coin="update counternotes set number="+ccrs10coins+" where note='rs10coin'";
        stmt.executeUpdate(sql10coin);
        
        
        String sql20="update counternotes set number="+ccrs20+" where note='rs20'";
        stmt.executeUpdate(sql20);
        
        
        String sql50="update counternotes set number="+ccrs50+" where note='rs50'";
        stmt.executeUpdate(sql50);
        
        
        String sql100="update counternotes set number="+ccrs100+" where note='rs100'";
        stmt.executeUpdate(sql100);
        
        
        String sql200="update counternotes set number="+ccrs200+" where note='rs200'";
        stmt.executeUpdate(sql200);
        
        
        String sql500="update counternotes set number="+ccrs500+" where note='rs500'";
        stmt.executeUpdate(sql500);
        
        
        
        String sql2000="update counternotes set number="+ccrs2000+" where note='rs2000'";
        stmt.executeUpdate(sql2000);
        
                }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
        }
            
        OutputToCustomer otc = new OutputToCustomer();
        otc.setVisible(true);
        this.setVisible(false);
        }}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        jTextField2.setText((Integer.parseInt(jTextField2.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button13ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        jTextField2.setText((Integer.parseInt(jTextField2.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button14ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        jTextField3.setText((Integer.parseInt(jTextField3.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button11ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        jTextField4.setText((Integer.parseInt(jTextField4.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        jTextField4.setText((Integer.parseInt(jTextField4.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        jTextField11.setText((Integer.parseInt(jTextField11.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        jTextField11.setText((Integer.parseInt(jTextField11.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        jTextField10.setText((Integer.parseInt(jTextField10.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        jTextField10.setText((Integer.parseInt(jTextField10.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        jTextField9.setText((Integer.parseInt(jTextField9.getText())-1)+"");            // TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        jTextField9.setText((Integer.parseInt(jTextField9.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        jTextField8.setText((Integer.parseInt(jTextField8.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button9ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        jTextField8.setText((Integer.parseInt(jTextField8.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button10ActionPerformed

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button19ActionPerformed
        jTextField5.setText((Integer.parseInt(jTextField5.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button19ActionPerformed

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button18ActionPerformed
        jTextField6.setText((Integer.parseInt(jTextField6.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button18ActionPerformed

    private void button17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button17ActionPerformed
        jTextField6.setText((Integer.parseInt(jTextField6.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button17ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed
        jTextField7.setText((Integer.parseInt(jTextField7.getText())-1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button16ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        jTextField7.setText((Integer.parseInt(jTextField7.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button15ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
        jTextField5.setText((Integer.parseInt(jTextField5.getText())-1)+"");        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_button20ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        jTextField3.setText((Integer.parseInt(jTextField3.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
CounterNoteSet cns = new CounterNoteSet();
        cns.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed
        jTextField13.setText((Integer.parseInt(jTextField13.getText())+1)+"");        // TODO add your handling code here:
    }//GEN-LAST:event_button21ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed
        jTextField13.setText((Integer.parseInt(jTextField13.getText())-1)+"");            // TODO add your handling code here:
    }//GEN-LAST:event_button22ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button14;
    private java.awt.Button button15;
    private java.awt.Button button16;
    private java.awt.Button button17;
    private java.awt.Button button18;
    private java.awt.Button button19;
    private java.awt.Button button2;
    private java.awt.Button button20;
    private java.awt.Button button21;
    private java.awt.Button button22;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
