/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magicbill;

/**
 *
 * @author Hameed Ahmed
 */
public class OutputToCustomer extends javax.swing.JFrame {

    /**
     * Creates new form OutputToCustomer
     */
    public OutputToCustomer() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        //setting output amount
        jTextField2.setText(GlobalClass.oprs1+"");
        jTextField3.setText(GlobalClass.oprs2+"");
        jTextField4.setText(GlobalClass.oprs5+"");
        jTextField11.setText(GlobalClass.oprs10+"");
        jTextField13.setText(GlobalClass.oprs10coin+"");
        jTextField10.setText(GlobalClass.oprs20+"");
        jTextField9.setText(GlobalClass.oprs50+"");
        jTextField8.setText(GlobalClass.oprs100+"");
        jTextField7.setText(GlobalClass.oprs200+"");
        jTextField6.setText(GlobalClass.oprs500+"");
        jTextField5.setText(GlobalClass.oprs2000+"");
        jTextField1.setText(GlobalClass.invamt+"");
        System.out.println(GlobalClass.ipamt+"   "+GlobalClass.invamt);
        jTextField12.setText((GlobalClass.ipamt-GlobalClass.invamt)+"");
        
        
        if(GlobalClass.oprs1==0)
        {
            jLabel9.setEnabled(false);
            jTextField2.setEnabled(false);
        }
        
        if(GlobalClass.oprs2==0)
        {
            jLabel10.setEnabled(false);
            jTextField3.setEnabled(false);
        }
        
        if(GlobalClass.oprs5==0)
        {
            jLabel11.setEnabled(false);
            jTextField4.setEnabled(false);
        }
        
        if(GlobalClass.oprs10==0)
        {
            jLabel6.setEnabled(false);
            jTextField11.setEnabled(false);
        }
        
        if(GlobalClass.oprs10coin==0)
        {
            jLabel16.setEnabled(false);
            jTextField13.setEnabled(false);
        }
        
        if(GlobalClass.oprs20==0)
        {
            jLabel5.setEnabled(false);
            jTextField10.setEnabled(false);
        }
        
        if(GlobalClass.oprs50==0)
        {
            jLabel3.setEnabled(false);
            jTextField9.setEnabled(false);
        }
        
        if(GlobalClass.oprs100==0)
        {
            jLabel1.setEnabled(false);
            jTextField8.setEnabled(false);
        }
        
        if(GlobalClass.oprs200==0)
        {
            jLabel7.setEnabled(false);
            jTextField7.setEnabled(false);
        }
        
        
        if(GlobalClass.oprs500==0)
        {
            jLabel8.setEnabled(false);
            jTextField6.setEnabled(false);
        }
        
        
        if(GlobalClass.oprs2000==0)
        {
            jLabel4.setEnabled(false);
            jTextField5.setEnabled(false);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField2.setText("0");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(40, 410, 85, 30);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField3.setText("0");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 410, 85, 30);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField4.setText("0");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(360, 410, 85, 30);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField7.setText("0");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(1160, 30, 85, 30);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField6.setText("0");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(1160, 230, 85, 30);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField5.setText("0");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(1160, 430, 85, 30);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField8.setText("0");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(640, 630, 85, 30);

        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField9.setText("0");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(640, 430, 85, 30);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField10.setText("0");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(640, 230, 85, 30);

        jTextField11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField11.setText("0");
        getContentPane().add(jTextField11);
        jTextField11.setBounds(640, 30, 85, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Output Denominations to customer:-");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 20, 459, 71);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs1 coin png.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 450, 110, 110);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs2 coin png.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 450, 110, 110);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 5 png.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(350, 450, 120, 110);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs10 new.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(640, 60, 349, 156);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs20 new.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 260, 349, 156);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 50 new.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 460, 348, 156);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 200 new.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1160, 60, 350, 156);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 500 new.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1160, 260, 350, 156);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs 2000 new.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1160, 460, 350, 156);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs100 new.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(640, 660, 350, 150);

        jTextField13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField13.setText("0");
        getContentPane().add(jTextField13);
        jTextField13.setBounds(200, 580, 90, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rs10 coin.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(190, 610, 120, 120);

        jPanel1.setBackground(new java.awt.Color(51, 227, 216));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 3, true));
        jPanel1.setForeground(new java.awt.Color(0, 102, 204));
        jPanel1.setOpaque(false);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Continue with other customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Invoice Amount:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Change Back:");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField12)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 40, 570, 350);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rotated1.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1500, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    MainForm mfo=new MainForm();
    mfo.setVisible(true);
    this.setVisible(false);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputToCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputToCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputToCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputToCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputToCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
